# Generated by Django 3.0 on 2021-11-02 22:57

from django.db import migrations


def transfert_profiles(apps, schema_editor):
    try:
        OldProfile = apps.get_model("oc_lettings_site", "Profile")
        NewProfile = apps.get_model("profiles", "Profile")
        for profile in OldProfile.objects.all():
            NewProfile.objects.create(
                user=profile.user, favorite_city=profile.favorite_city
            )
    except LookupError:
        print("Pascaline a raté quelque chose dans sa mise en place :P")
        return


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(transfert_profiles),
    ]
    